//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znode.Custom.Data
{
    using System;
    using System.Collections.Generic;
    using Znode.Libraries.Data;
    public partial class CustomUOMRule : ZnodeEntityBaseModel
    {
        public string UOM { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int UniqueId { get; set; }
    }
}
