//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9040
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BOXFrghtEstSoap", Namespace="https://www.boxpartners.com/boxws/")]
public partial class BOXFrghtEst : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetFreightEstimateOperationCompleted;
    
    private System.Threading.SendOrPostCallback FreightEstimateOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetFreightEstimateExcludeLocalTruckOperationCompleted;
    
    /// <remarks/>
    public BOXFrghtEst() {
        this.Url = "https://www.boxpartners.com/boxws/boxfrghtest.asmx";
    }
    
    /// <remarks/>
    public event GetFreightEstimateCompletedEventHandler GetFreightEstimateCompleted;
    
    /// <remarks/>
    public event FreightEstimateCompletedEventHandler FreightEstimateCompleted;
    
    /// <remarks/>
    public event GetFreightEstimateExcludeLocalTruckCompletedEventHandler GetFreightEstimateExcludeLocalTruckCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.boxpartners.com/boxws/GetFreightEstimate", RequestNamespace="https://www.boxpartners.com/boxws/", ResponseNamespace="https://www.boxpartners.com/boxws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Carrier[] GetFreightEstimate(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode) {
        object[] results = this.Invoke("GetFreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode});
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetFreightEstimate(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public Carrier[] EndGetFreightEstimate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public void GetFreightEstimateAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode) {
        this.GetFreightEstimateAsync(BOXItems, CustNum, Password, ZipCode, StateCode, null);
    }
    
    /// <remarks/>
    public void GetFreightEstimateAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, object userState) {
        if ((this.GetFreightEstimateOperationCompleted == null)) {
            this.GetFreightEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFreightEstimateOperationCompleted);
        }
        this.InvokeAsync("GetFreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode}, this.GetFreightEstimateOperationCompleted, userState);
    }
    
    private void OnGetFreightEstimateOperationCompleted(object arg) {
        if ((this.GetFreightEstimateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetFreightEstimateCompleted(this, new GetFreightEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.boxpartners.com/boxws/FreightEstimate", RequestNamespace="https://www.boxpartners.com/boxws/", ResponseNamespace="https://www.boxpartners.com/boxws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Carrier[] FreightEstimate(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, bool IsResidential) {
        object[] results = this.Invoke("FreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode,
                    IsResidential});
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFreightEstimate(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, bool IsResidential, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode,
                    IsResidential}, callback, asyncState);
    }
    
    /// <remarks/>
    public Carrier[] EndFreightEstimate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public void FreightEstimateAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, bool IsResidential) {
        this.FreightEstimateAsync(BOXItems, CustNum, Password, ZipCode, StateCode, IsResidential, null);
    }
    
    /// <remarks/>
    public void FreightEstimateAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, bool IsResidential, object userState) {
        if ((this.FreightEstimateOperationCompleted == null)) {
            this.FreightEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFreightEstimateOperationCompleted);
        }
        this.InvokeAsync("FreightEstimate", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode,
                    IsResidential}, this.FreightEstimateOperationCompleted, userState);
    }
    
    private void OnFreightEstimateOperationCompleted(object arg) {
        if ((this.FreightEstimateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FreightEstimateCompleted(this, new FreightEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.boxpartners.com/boxws/GetFreightEstimateExcludeLocalTruck", RequestNamespace="https://www.boxpartners.com/boxws/", ResponseNamespace="https://www.boxpartners.com/boxws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Carrier[] GetFreightEstimateExcludeLocalTruck(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode) {
        object[] results = this.Invoke("GetFreightEstimateExcludeLocalTruck", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode});
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetFreightEstimateExcludeLocalTruck(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetFreightEstimateExcludeLocalTruck", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public Carrier[] EndGetFreightEstimateExcludeLocalTruck(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Carrier[])(results[0]));
    }
    
    /// <remarks/>
    public void GetFreightEstimateExcludeLocalTruckAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode) {
        this.GetFreightEstimateExcludeLocalTruckAsync(BOXItems, CustNum, Password, ZipCode, StateCode, null);
    }
    
    /// <remarks/>
    public void GetFreightEstimateExcludeLocalTruckAsync(BOXItem[] BOXItems, string CustNum, string Password, string ZipCode, string StateCode, object userState) {
        if ((this.GetFreightEstimateExcludeLocalTruckOperationCompleted == null)) {
            this.GetFreightEstimateExcludeLocalTruckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFreightEstimateExcludeLocalTruckOperationCompleted);
        }
        this.InvokeAsync("GetFreightEstimateExcludeLocalTruck", new object[] {
                    BOXItems,
                    CustNum,
                    Password,
                    ZipCode,
                    StateCode}, this.GetFreightEstimateExcludeLocalTruckOperationCompleted, userState);
    }
    
    private void OnGetFreightEstimateExcludeLocalTruckOperationCompleted(object arg) {
        if ((this.GetFreightEstimateExcludeLocalTruckCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetFreightEstimateExcludeLocalTruckCompleted(this, new GetFreightEstimateExcludeLocalTruckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.boxpartners.com/boxws/")]
public partial class BOXItem {
    
    private string itemCodeField;
    
    private int quantityField;
    
    /// <remarks/>
    public string ItemCode {
        get {
            return this.itemCodeField;
        }
        set {
            this.itemCodeField = value;
        }
    }
    
    /// <remarks/>
    public int Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.boxpartners.com/boxws/")]
public partial class Carrier {
    
    private string carrierIDField;
    
    private string carrierNameField;
    
    private decimal freightTotalField;
    
    /// <remarks/>
    public string CarrierID {
        get {
            return this.carrierIDField;
        }
        set {
            this.carrierIDField = value;
        }
    }
    
    /// <remarks/>
    public string CarrierName {
        get {
            return this.carrierNameField;
        }
        set {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    public decimal FreightTotal {
        get {
            return this.freightTotalField;
        }
        set {
            this.freightTotalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetFreightEstimateCompletedEventHandler(object sender, GetFreightEstimateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetFreightEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetFreightEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Carrier[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Carrier[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void FreightEstimateCompletedEventHandler(object sender, FreightEstimateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FreightEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal FreightEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Carrier[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Carrier[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void GetFreightEstimateExcludeLocalTruckCompletedEventHandler(object sender, GetFreightEstimateExcludeLocalTruckCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetFreightEstimateExcludeLocalTruckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetFreightEstimateExcludeLocalTruckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Carrier[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Carrier[])(this.results[0]));
        }
    }
}
